name: Publish Library to crates.io

on:
  workflow_dispatch: {}
  workflow_call: {}

jobs:
  publish:
    name: Publish vvf to crates.io
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal

      - name: Verify Cargo.toml
        working-directory: core
        run: cargo package --allow-dirty

      - name: Publish to crates.io
        working-directory: core
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_TOKEN }}
        run: cargo publish --allow-dirty
